"use strict";

var StampGroup = {
	Decor:1,
	Doors:2, 
	Hazards:3,
	Markers:4,
	Nature:5,
    Magic: 6,
	Numbers:7,
	Structural:8,
    Monsters: 9,
	Weapons: 10,
    Garden: 11,
    Custom: 12,
}

var StampGroupName = ["","Decor", "Doors", "Hazards", "Markers", "Nature", "Magic", "Numbers", "Structural", "Monsters", "Weapons", "Garden", "Custom"];

var StampConstants = {
    Stairs: {
		path:'stamps/AL3/stairs.svg',
		name: "Stairs",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
    Door: {
		path:'stamps/AL3/al_door.svg',
		name: "Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	DoorSecret: {
		path:'stamps/AL3/al_door_secret.svg',
		name: "Secret Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	DoorBlocked: {
		path:'stamps/AL3/al_door_blocked.svg',
		name: "Blocked Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
    DoorPortcullis: {
		path:'stamps/AL3/iron_bar.svg',
		name: "Iron Bars",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
    Num0:{
		path:'stamps/numbers/0circ.png',
		name: "Number 1",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
    Num1:{
		path:'stamps/numbers/1circ.png',
		name: "Number 1",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
    Num2:{
		path:'stamps/numbers/2circ.png',
		name: "Number 1",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
    Num3:{
		path:'stamps/numbers/3circ.png',
		name: "Number 1",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
    Num4:{
		path:'stamps/numbers/4circ.png',
		name: "Number 1",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
    Num5:{
		path:'stamps/numbers/5circ.png',
		name: "Number 1",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
    Num6:{
		path:'stamps/numbers/6circ.png',
		name: "Number 1",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
    Num7:{
		path:'stamps/numbers/7circ.png',
		name: "Number 1",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
    Num8:{
		path:'stamps/numbers/8circ.png',
		name: "Number 1",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
    Num9:{
		path:'stamps/numbers/9circ.png',
		name: "Number 1",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
    Star:{
		path:'stamps/markers/starcircle.png',
		name: "Statue",
		alias: "star",
		group: StampGroup.Markers,
		defMult: 1,
	},
    Throne: {
		path:'stamps/decor/throne.svg',
		name: "Throne",
		alias: "",
		group: StampGroup.Decor,
		defMult: 2,
	},
    Barrel:{
		path:'stamps/decor/barrel_side.svg',
		name: "Barrel Side",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
    Crack:{
		path:'stamps/hazards/crack1.svg',
		name: "Crack",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
    Pit:{
		path:'stamps/hazards/pit.svg',
		name: "Pit",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
    Chest:{
		path:'stamps/decor/chest.svg',
		name: "Treasure Chest",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
    Bed:{
		path:'stamps/decor/bed.svg',
		name: "Bed",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
    Goblin_Grunt:{
		path:'stamps/monsters/goblin_grunt.svg',
		name: "Goblin Grunt",
		alias: "goblin, monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	Goblin_Sapper:{
		path:'stamps/monsters/goblin_sapper.svg',
		name: "Goblin Sapper",
		alias: "goblin, sapper, monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	Ogre:{
		path:'stamps/monsters/ogre.svg',
		name: "Ogre",
		alias: "ogre, monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	Skeleton_Grunt:{
		path:'stamps/monsters/skellington_grunt.svg',
		name: "Skeleton Grunt",
		alias: "skeleton, monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	Skeleton_Captain:{
		path:'stamps/monsters/skellington_capitan.svg',
		name: "Skeleton Captain",
		alias: "skeleton, captain, monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
    Giant:{
		path:'stamps/monsters/giant.svg',
		name: "Giant",
		alias: "giant, monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	Orc:{
		path:'stamps/monsters/orc.svg',
		name: "Orc",
		alias: "orc, monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	Elf:{
		path:'stamps/monsters/elf.svg',
		name: "Elf",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	Halfling_Gnome:{
		path:'stamps/monsters/halfling-gnome.svg',
		name: "Halfling Gnome",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	Draconid:{
		path:'stamps/monsters/draconid.svg',
		name: "Draconid",
		alias: "dragon, monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
}


var Stamps = [
	{
		path:'stamps/decor/barrel_side.svg',
		name: "Barrel Side",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/decor/barrel_top.svg',
		name: "Barrel Top",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/decor/bed.svg',
		name: "Bed",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/decor/chair.svg',
		name: "Chair",
		alias: "",
		group: StampGroup.Decor,
		defMult: 0.5,
	},
	{
		path:'stamps/decor/throne.svg',
		name: "Throne",
		alias: "",
		group: StampGroup.Decor,
		defMult: 2,
	},
	{
		path:'stamps/decor/weaponrack1.svg',
		name: "Weapon Rack",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/decor/weaponrack2.svg',
		name: "Weapon Rack",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/hazards/crack1.svg',
		name: "Crack",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
	{
		path:'stamps/hazards/crack2.svg',
		name: "Crack",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
	{
		path:'stamps/hazards/pit.svg',
		name: "Pit",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
	{
		path:'stamps/nature/campfire_lit.svg',
		name: "Lit Campfire",
		alias: "",
		group: StampGroup.Nature,
		defMult: 0.5,
	},
	{
		path:'stamps/nature/campfire_unlit.svg',
		name: "Unlit Campfire",
		alias: "",
		group: StampGroup.Nature,
		defMult: 0.5,
	},
	{
		path:'stamps/nature/tent.svg',
		name: "Tent",
		alias: "",
		group: StampGroup.Nature,
		defMult: 2,
	},
	{
		path:'stamps/nature/pond.svg',
		name: "Pond",
		alias: "lake, water",
		group: StampGroup.Nature,
		defMult: 2,
	},
	{
		path:'stamps/decor/desk.svg',
		name: "Desk",
		alias: "table, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	/////////////
	{
		path:'stamps/decor/desk_cluttered.svg',
		name: "Cluttered Desk",
		alias: "table, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/decor/chest.svg',
		name: "Treasure Chest",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/decor/crate.svg',
		name: "Crate",
		alias: "box, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/nature/rock.svg',
		name: "Rocks",
		alias: "stone, pebble, rubble",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/nature/rubble.svg',
		name: "Rubble",
		alias: "stone, pebble, rocks",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/nature/rubble_sand.svg',
		name: "Sand Rubble",
		alias: "stone, pebble, rocks",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/walls/pillar.svg',
		name: "Pillar",
		alias: "pole",
		group: StampGroup.Structural,
		defMult: 1,
	},
	{
		path:'stamps/walls/pillar2.svg',
		name: "Pillar",
		alias: "pole",
		group: StampGroup.Structural,
		defMult: 1,
	},
	{
		path:'stamps/walls/pillar_sand.svg',
		name: "Sand Pillar",
		alias: "pole",
		group: StampGroup.Structural,
		defMult: 1,
	},
	{
		path:'stamps/walls/pillar_sand2.svg',
		name: "Sand Pillar",
		alias: "pole",
		group: StampGroup.Structural,
		defMult: 1,
	},
	//Stamp Pack 3
	{
		path:'stamps/AL3/al_door.svg',
		name: "Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/AL3/al_door_secret.svg',
		name: "Secret Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/AL3/al_door_1way.svg',
		name: "1 Way Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/AL3/al_door_blocked.svg',
		name: "Blocked Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/AL3/al_door_trans.svg',
		name: "Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/AL3/al_door_secret_trans.svg',
		name: "Secret Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/AL3/al_door_1way_trans.svg',
		name: "1 Way Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/AL3/al_door_blocked_trans.svg',
		name: "Blocked Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/AL3/bush.svg',
		name: "Bush",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/bush_trans.svg',
		name: "Bush Transparent",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/tree.svg',
		name: "Tree",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/tree_trans.svg',
		name: "Tree Transparent",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/cage.svg',
		name: "Cage",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/coffin.svg',
		name: "Coffin",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/coffin_trans.svg',
		name: "",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/stairs.svg',
		name: "Stairs",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/curved_stairs.svg',
		name: "Curved Stairs",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/dirt.svg',
		name: "Grave Patch",
		alias: "dirt",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/dirt_trans.svg',
		name: "Grave Patch Transparent",
		alias: "dirt",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/gear1.svg',
		name: "",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/gear2.svg',
		name: "",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/gear3.svg',
		name: "Gear",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/gear4.svg',
		name: "Gear",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/iron_bar.svg',
		name: "Iron Bars",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/AL3/iron_gate.svg',
		name: "Iron Gate",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/AL3/mushroom1.svg',
		name: "Mushrooms",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/mushroom2.svg',
		name: "Mushrooms",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/pot1.svg',
		name: "Pots",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/pot2.svg',
		name: "Pots",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/sarcophagus.svg',
		name: "Sarcophagus",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/sarcophagus_trans.svg',
		name: "Sarcophagus Transparent",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/skeleton1.svg',
		name: "Skeleton",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/skeleton2.svg',
		name: "Skeleton",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/AL3/tombstone1.svg',
		name: "Tombstone",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/tombstone2.svg',
		name: "Tombstone",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/tombstone1_trans.svg',
		name: "Tombstone Transparent",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/tombstone2_trans.svg',
		name: "Tombstone Transparent",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/AL3/trapdoor.svg',
		name: "Trapdoor",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
	{
		path:'stamps/AL3/trapdoor2.svg',
		name: "Trapdoor",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
	//Compass
	{
		path:'stamps/markers/compass_polearm.svg',
		name: "Compass - Polearm",
		alias: "rose",
		group: StampGroup.Markers,
		defMult: 2.5,
	},
	{
		path:'stamps/markers/compass_sword.svg',
		name: "Compass - Sword",
		alias: "rose",
		group: StampGroup.Markers,
		defMult: 2.5,
	},
	{
		path:'stamps/markers/compass_spear.svg',
		name: "Compass - Spear",
		alias: "rose",
		group: StampGroup.Markers,
		defMult: 2.5,
	},
    //AL4
    {
		path:'stamps/hazards/beartrap.svg',
		name: "Bear Trap",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
    {
		path:'stamps/hazards/maneatingflower.svg',
		name: "Man Eating Flower",
		alias: "venus fly trap",
		group: StampGroup.Hazards,
		defMult: 1,
	},
    {
		path:'stamps/hazards/quicksand.svg',
		name: "Quicksand",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
    {
		path:'stamps/hazards/slime.svg',
		name: "Green Slime",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
    {
		path:'stamps/hazards/spikes.svg',
		name: "Spikes",
		alias: "floor",
		group: StampGroup.Hazards,
		defMult: 1,
	},
    {
		path:'stamps/hazards/wallspike.svg',
		name: "Arrow Trap",
		alias: "wall spikes",
		group: StampGroup.Hazards,
		defMult: 1,
	},
    {
		path:'stamps/hazards/web1.svg',
		name: "Spider Web",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
    {
		path:'stamps/hazards/web2.svg',
		name: "Spider Web",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
    {
		path:'stamps/hazards/web3.svg',
		name: "Spider Web",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
    {
		path:'stamps/hazards/web4.svg',
		name: "Spider Web",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
	
	//DungeonStuff
	
	{
		path:'stamps/dungeonstuff/1125573-Bookcase 1-1x1.png',
		name: "Bookcase",
		alias: "books, shelf",
		group: StampGroup.Decor,
		defMult: 1,
	},
	
	{
		path:'stamps/dungeonstuff/1125579-Bookcase 4-2x1.png',
		name: "Bookcase",
		alias: "books, shelf",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125585-Bookcase 7-2x2.png',
		name: "Bookcase",
		alias: "books, shelf",
		group: StampGroup.Decor,
		defMult: 2,
	},
	{
		path:'stamps/dungeonstuff/1125611-Casket 1-2x1.png',
		name: "Casket",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125613-Casket 2-2x1.png',
		name: "Casket",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125615-Casket 3-2x1.png',
		name: "Casket",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125617-Chair 1-1x1.png',
		name: "Chair",
		alias: "",
		group: StampGroup.Decor,
		defMult: 0.5,
	},
	{
		path:'stamps/dungeonstuff/1125623-Chair 4-1x1.png',
		name: "Chair",
		alias: "",
		group: StampGroup.Decor,
		defMult: 0.5,
	},
	{
		path:'stamps/dungeonstuff/1125629-Chair 7-1x1.png',
		name: "Chair",
		alias: "",
		group: StampGroup.Decor,
		defMult: 0.5,
	},
	{
		path:'stamps/dungeonstuff/1125639-Chest 3-1x1.png',
		name: "Treasure Chest Closed",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125645-Chest-Open 3-1x1.png',
		name: "Treasure Chest Open",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125699-Desk 1-1x2.png',
		name: "Desk",
		alias: "table, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125707-Desk-Things 1-1x2.png',
		name: "Cluttered Desk",
		alias: "table, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125709-Desk-Things 2-1x2.png',
		name: "Cluttered Desk",
		alias: "table, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125711-Desk-Things 3-1x2.png',
		name: "Cluttered Desk",
		alias: "table, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125713-Desk-Things 4-1x2.png',
		name: "Cluttered Desk",
		alias: "table, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125799-Pond 1-1x1.png',
		name: "Pond",
		alias: "water, lake, fountain",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125801-Pond 2-1x1.png',
		name: "Pond",
		alias: "water, lake, fountain",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125803-Pond 3-2x2.png',
		name: "Pond",
		alias: "water, lake, fountain",
		group: StampGroup.Nature,
		defMult: 2,
	},
	{
		path:'stamps/dungeonstuff/1125805-Pond 4-2x2.png',
		name: "Pond",
		alias: "water, lake, fountain",
		group: StampGroup.Nature,
		defMult: 2,
	},
	{
		path:'stamps/dungeonstuff/1125809-Rug 1-2x1.png',
		name: "Rug 2x1",
		alias: "carpet, floor",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125811-Rug 2-2x1.png',
		name: "Rug 2x1",
		alias: "carpet, floor",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125813-Rug 3-2x1.png',
		name: "Rug 2x1",
		alias: "carpet, floor",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125815-Rug 4-2x1.png',
		name: "Rug 2x1",
		alias: "carpet, floor",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125817-Rug 5-2x2.png',
		name: "Rug 1x1",
		alias: "carpet, floor",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125819-Rug 6-2x2.png',
		name: "Rug 1x1",
		alias: "carpet, floor",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125821-Rug 7-2x2.png',
		name: "Rug 1x1",
		alias: "carpet, floor",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125823-Rug 8-4x2.png',
		name: "Rug 2x1",
		alias: "carpet, floor",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125825-Rug 9-4x2.png',
		name: "Rug 2x1",
		alias: "carpet, floor",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125905-Table-Things 7-2x1.png',
		name: "Table",
		alias: "desk, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125907-Table-Things 8-2x1.png',
		name: "Table",
		alias: "desk, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125909-Table-Things 9-2x1.png',
		name: "Table",
		alias: "desk, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125911-Table-Things 10-2x1.png',
		name: "Table",
		alias: "desk, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125917-Table-Things 13-2x1.png',
		name: "Table",
		alias: "desk, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125919-Table-Things 14-2x1.png',
		name: "Table",
		alias: "desk, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125921-Table-Things 15-2x1.png',
		name: "Table",
		alias: "desk, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125923-Table-Things 16-2x1.png',
		name: "Table",
		alias: "desk, wood",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125609-Bust 1x1.png',
		name: "Suit of Armor",
		alias: "statue, bust",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/dungeonstuff/1125769-Magic Circle 1-2x2.png',
		name: "Magic Circle",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 2,
	},
	{
		path:'stamps/dungeonstuff/1125771-Magic Circle 2-2x2.png',
		name: "Magic Circle",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 2,
	},
	{
		path:'stamps/dungeonstuff/1125773-Magic Circle 3-2x2.png',
		name: "Magic Circle",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 2,
	},
	{
		path:'stamps/dungeonstuff/1125775-Magic Circle 4-3x3.png',
		name: "Magic Circle",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 2,
	},
	{
		path:'stamps/dungeonstuff/1125777-Magic Circle 5-3x3.png',
		name: "Magic Circle",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 2,
	},
	{
		path:'stamps/dungeonstuff/1125779-Magic Circle 6-3x3.png',
		name: "Magic Circle",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 2,
	},
    {
		path:'stamps/dungeonstuff/1125781-Magic Circle 7-3x3.png',
		name: "Magic Circle",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 2,
	},
    {
		path:'stamps/dungeonstuff/1125827-Seal 1-1x1.png',
		name: "Seal",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/1125829-Seal 2-1x1.png',
		name: "Seal",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/1125831-Seal 3-1x1.png',
		name: "Seal",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/1125833-Seal 4-1x1.png',
		name: "Seal",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/1125835-Seal 5-1x1.png',
		name: "Seal",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/1125837-Seal 6-1x1.png',
		name: "Seal",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/1125839-Seal 7-1x1.png',
		name: "Seal",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/1125841-Seal 8-1x1.png',
		name: "Seal",
		alias: "Sigil",
		group: StampGroup.Magic,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/1125559-Armor 5-2x2.png',
		name: "Suit of Armour",
		alias: "armor, statue",
		group: StampGroup.Decor,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/1125551-Armor 1-2x2.png',
		name: "Suit of Armour",
		alias: "armor, statue",
		group: StampGroup.Decor,
		defMult: 1,
	},
  /*  {
		path:'stamps/dungeonstuff/.png',
		name: "",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/.png',
		name: "",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/.png',
		name: "",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
    {
		path:'stamps/dungeonstuff/.png',
		name: "",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},*/
	
	///////////Old hand drawn stuff
	
	
	{
		path:'star.png',
		name: "Statue",
		alias: "star",
		group: StampGroup.Markers,
		defMult: 1,
	},
	{
		path:'stairs_left.png',
		name: "Stairs",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stairs_right.png',
		name: "Stairs",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stairs_up.png',
		name: "Stairs",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stairs_down.png',
		name: "Stairs",
		alias: "",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'door_up_down.png',
		name: "Door Up/Down",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'door_left_right.png',
		name: "Door Left/Right",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/numbers/0circ.png',
		name: "Number 0",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
	{
		path:'stamps/numbers/1circ.png',
		name: "Number 1",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
	{
		path:'stamps/numbers/2circ.png',
		name: "Number 2",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
	{
		path:'stamps/numbers/3circ.png',
		name: "Number 3",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
	{
		path:'stamps/numbers/4circ.png',
		name: "Number 4",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
	{
		path:'stamps/numbers/5circ.png',
		name: "Number 5",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
	{
		path:'stamps/numbers/6circ.png',
		name: "Number 6",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
	{
		path:'stamps/numbers/7circ.png',
		name: "Number 7",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
	{
		path:'stamps/numbers/8circ.png',
		name: "Number 8",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
	{
		path:'stamps/numbers/9circ.png',
		name: "Number 9",
		alias: "",
		group: StampGroup.Numbers,
		defMult: 1,
	},
	{
		path:'stamps/decor/barrelside.png',
		name: "Barrel Side",
		alias: "drawn",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/decor/bed.png',
		name: "Bed",
		alias: "drawn",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/decor/chair.png',
		name: "Chair",
		alias: "drawn",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/decor/chest.png',
		name: "Treasure Chest",
		alias: "drawn",
		group: StampGroup.Decor,
		defMult: 1,
	},
	{
		path:'stamps/doors/door.png',
		name: "Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/doors/doubledoor.png',
		name: "Double Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/doors/lockeddoor.png',
		name: "Locked Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/doors/secretdoor.png',
		name: "Secret Door",
		alias: "",
		group: StampGroup.Doors,
		defMult: 1,
	},
	{
		path:'stamps/hazards/cracks.png',
		name: "Cracks",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
	{
		path:'stamps/hazards/pit.png',
		name: "Pit",
		alias: "",
		group: StampGroup.Hazards,
		defMult: 1,
	},
	{
		path:'stamps/markers/city.png',
		name: "City",
		alias: "",
		group: StampGroup.Markers,
		defMult: 1,
	},
	{
		path:'stamps/markers/flag.png',
		name: "Flag",
		alias: "",
		group: StampGroup.Markers,
		defMult: 1,
	},
	{
		path:'stamps/markers/starcircle.png',
		name: "Statue",
		alias: "star",
		group: StampGroup.Markers,
		defMult: 1,
	},
	{
		path:'stamps/nature/cave.png',
		name: "Cave",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/nature/hills.png',
		name: "Hills",
		alias: "",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/nature/pond.png',
		name: "Pond",
		alias: "water, lake",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/nature/rocks.png',
		name: "Rocks",
		alias: "pebbles, stone",
		group: StampGroup.Nature,
		defMult: 1,
	},
	{
		path:'stamps/monsters/goblin_grunt.svg',
		name: "Goblin Grunt",
		alias: "goblin, monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	{
		path:'stamps/monsters/goblin_sapper.svg',
		name: "Goblin Sapper",
		alias: "goblin, sapper, monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	{
		path:'stamps/monsters/ogre.svg',
		name: "Ogre",
		alias: "ogre, monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/skellington_grunt.svg',
		name: "Skeleton Grunt",
		alias: "skeleton, monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	{
		path:'stamps/monsters/skellington_capitan.svg',
		name: "Skeleton Captain",
		alias: "skeleton, captain, monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	{
		path:'stamps/monsters/giant.svg',
		name: "Giant",
		alias: "giant, monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/orc.svg',
		name: "Orc",
		alias: "orc, monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	{
		path:'stamps/monsters/elf.svg',
		name: "Elf",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	{
		path:'stamps/monsters/halfling-gnome.svg',
		name: "Halfling Gnome",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
	},
	{
		path:'stamps/monsters/draconid.svg',
		name: "Draconid",
		alias: "dragon, monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/beholder.svg',
		name: "Beholder",
		alias: "beholder, monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/drow.svg',
		name: "Drow",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/fungus-monster.svg',
		name: "Fungus Monster",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/gelatinous-cube.svg',
		name: "Gelatinous Cube",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/kobold_modern.svg',
		name: "Kobold",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/kobold-classic.svg',
		name: "Kobold",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/lich.svg',
		name: "Lich",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/mimic.svg',
		name: "Mimic",
		alias: "chest, monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/mindflayer.svg',
		name: "Mind Flayer",
		alias: "mindflayer, monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/owlbear.svg',
		name: "Owlbear",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/rust-monster.svg',
		name: "Rust Monster",
		alias: "dragon, monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	{
		path:'stamps/monsters/vampire.svg',
		name: "Vampire",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 2,
	},
	////////////////////
	{
		path:'stamps/weapons/ammo-box.svg',
		name: "ammo box",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/anti-aircraft-gun.svg',
		name: "anti aircraft gun",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/archery-target.svg',
		name: "archery target",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/armored-boomerang.svg',
		name: "armored boomerang",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/arrowhead.svg',
		name: "arrowhead",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/axe-in-stump.svg',
		name: "axe in stump",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/baseball-bat.svg',
		name: "baseball bat",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/battered-axe.svg',
		name: "battered axe",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/battle-axe.svg',
		name: "battle axe",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/blunderbuss.svg',
		name: "blunderbuss",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/bo.svg',
		name: "bo",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/bone-mace.svg',
		name: "bone mace",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/boomerang.svg',
		name: "boomerang",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/bow-arrow.svg',
		name: "bow arrow",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/brass-knuckles.svg',
		name: "brass knuckles",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
	},
	{
		path:'stamps/weapons/bullets.svg',
		name: "bullets",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/cannon.svg',
		name: "cannon",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/crossed-pistols.svg',
		name: "crossed pistols",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/crossed-sabres.svg',
		name: "crossed sabres",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/crossed-swords.svg',
		name: "crossed swords",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/crowbar.svg',
		name: "crowbar",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/crystal-wand.svg',
		name: "crystal wand",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/fairy-wand.svg',
		name: "fairy wand",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/flail.svg',
		name: "flail",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/flanged-mace.svg',
		name: "flanged mace",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/gladius.svg',
		name: "gladius",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/grapple.svg',
		name: "grapple",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/missile-launcher.svg',
		name: "missile launcher",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/monkey-wrench.svg',
		name: "monkey wrench",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/pistol-gun.svg',
		name: "pistol gun",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/scythe.svg',
		name: "scythe",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/sharp-shuriken.svg',
		name: "sharp shuriken",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/slingshot.svg',
		name: "slingshot",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/spiked-ball.svg',
		name: "spiked ball",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/spiked-bat.svg',
		name: "spiked bat",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/weapons/tomahawk.svg',
		name: "tomahawk",
		alias: "monster",
		group: StampGroup.Weapons,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/barbed-wire.svg',
		name: "barbed wire",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/box-trap.svg',
		name: "box trap",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/caltrops.svg',
		name: "caltrops",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/cleaver.svg',
		name: "cleaver",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/crescent-blade.svg',
		name: "crescent blade",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/fire-ring.svg',
		name: "fire ring",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/fire-wave.svg',
		name: "fire wave",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/fishing-hook.svg',
		name: "fishing hook",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/fishing-net.svg',
		name: "fishing net",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/gibbet.svg',
		name: "gibbet",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/gift-trap.svg',
		name: "gift trap",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/hole.svg',
		name: "hole",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/land-mine.svg',
		name: "land mine",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/lever.svg',
		name: "lever",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/mantrap.svg',
		name: "mantrap",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/mimic-chest.svg',
		name: "mimic chest",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/quicksand2.svg',
		name: "quicksand",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/spiky-pit.svg',
		name: "spiky pit",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/stakes-fence.svg',
		name: "stakes fence",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/time-trap.svg',
		name: "time trap",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/tripwire.svg',
		name: "tripwire",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/venus-flytrap.svg',
		name: "venus flytrap",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/traps/wolf-trap.svg',
		name: "wolf trap",
		alias: "monster",
		group: StampGroup.Hazards,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/caldera.svg',
		name: "caldera",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/camping-tent.svg',
		name: "camping tent",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/cave-entrance.svg',
		name: "cave entrance",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/grass.svg',
		name: "grass",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/high-grass.svg',
		name: "high grass",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/holy-oak.svg',
		name: "holy oak",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/mountain-cave.svg',
		name: "mountain cave",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/pine-tree.svg',
		name: "pine tree",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/summits.svg',
		name: "summits",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/volcano.svg',
		name: "volcano",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/waterfall.svg',
		name: "waterfall",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/nature/wind-hole.svg',
		name: "wind hole",
		alias: "nature",
		group: StampGroup.Nature,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/anubis.svg',
		name: "anubis",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/behold.svg',
		name: "behold",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/bottled-shadow.svg',
		name: "bottled shadow",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/brain-tentacle.svg',
		name: "brain tentacle",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/brute.svg',
		name: "brute",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/bully-minion.svg',
		name: "bully minion",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/centaur.svg',
		name: "centaur",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/daemon-skull.svg',
		name: "daemon skull",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/devil-mask.svg',
		name: "devil mask",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/dinosaur-bones.svg',
		name: "dinosaur bones",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/dinosaur-rex.svg',
		name: "dinosaur rex",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/double-dragon.svg',
		name: "double dragon",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/dragon-head.svg',
		name: "dragon head",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/drakkar-dragon.svg',
		name: "drakkar dragon",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/egyptian-sphinx.svg',
		name: "egyptian sphinx",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/evil-book.svg',
		name: "evil book",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/evil-comet.svg',
		name: "evil comet",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/evil-minion.svg',
		name: "evil minion",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/fairy.svg',
		name: "fairy",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/fish-monster.svg',
		name: "fish monster",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/gargoyle.svg',
		name: "gargoyle",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/ghost.svg',
		name: "ghost",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/goblin-head.svg',
		name: "goblin head",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/gooey-daemon.svg',
		name: "gooey daemon",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/greek-sphinx.svg',
		name: "greek sphinx",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/griffin-symbol.svg',
		name: "griffin symbol",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/half-body-crawling.svg',
		name: "half body crawling",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/horus.svg',
		name: "horus",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/hydra.svg',
		name: "hydra",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/ice-golem.svg',
		name: "ice golem",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/kenku-head.svg',
		name: "kenku head",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/mermaid.svg',
		name: "mermaid",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/mimic-chest.svg',
		name: "mimic chest",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/minotaur.svg',
		name: "minotaur",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/mummy-head.svg',
		name: "mummy head",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/ogre2.svg',
		name: "ogre",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/oni.svg',
		name: "oni",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/orc-head.svg',
		name: "orc head",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/rock-golem.svg',
		name: "rock golem",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/sasquatch.svg',
		name: "sasquatch",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/sea-creature.svg',
		name: "sea creature",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/sea-dragon.svg',
		name: "sea dragon",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/shambling-zombie.svg',
		name: "shambling zombie",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/spectre.svg',
		name: "spectre",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/spiked-dragon-head.svg',
		name: "spiked dragon head",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/troll.svg',
		name: "troll",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/vile-fluid.svg',
		name: "vile fluid",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/werewolf.svg',
		name: "werewolf",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
	{
		path:'stamps/monsters/wyvern.svg',
		name: "wyvern",
		alias: "monster",
		group: StampGroup.Monsters,
		defMult: 1,
		canColour: true,
	},
    ///////GARDEN VEGETABLES
    {
		path:'stamps/garden/broccoli.svg',
		name: "broccoli",
		alias: "brassica",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/cabbage.svg',
		name: "cabbage",
		alias: "brassica",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/carrot.svg',
		name: "carrot",
		alias: "root",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/cauliflower.svg',
		name: "cauliflower",
		alias: "brassica",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/cayenne.svg',
		name: "cayenne",
		alias: "pepper",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/corn.svg',
		name: "corn",
		alias: "",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/cucumber.svg',
		name: "cucumber",
		alias: "",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/eggplant.svg',
		name: "eggplant",
		alias: "",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/garlic.svg',
		name: "garlic",
		alias: "allium",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/lettuce.svg',
		name: "lettuce",
		alias: "lettuce",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/mushroom.svg',
		name: "mushroom",
		alias: "",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/onion.svg',
		name: "onion",
		alias: "allium",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/peas.svg',
		name: "peas",
		alias: "beans",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/pepper.svg',
		name: "pepper",
		alias: "pepper",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/potato.svg',
		name: "potato",
		alias: "root",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/pumpkin.svg',
		name: "pumpkin",
		alias: "gourd",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/radish.svg',
		name: "radish",
		alias: "root",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/spinach.svg',
		name: "spinach",
		alias: "lettuce",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/tomato.svg',
		name: "tomato",
		alias: "",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/zucchini.svg',
		name: "zucchini",
		alias: "cucumber",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/tree1.png',
		name: "Tree",
		alias: "bush",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/tree2.png',
		name: "Tree",
		alias: "bush",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
    {
		path:'stamps/garden/tree3.png',
		name: "Tree",
		alias: "bush",
		group: StampGroup.Garden,
		defMult: 1,
		canColour: false,
	},
			
];

