var stylePresets = [
    {
        name: "Hand Drawn",
		img: "images/HandDrawn.png",
        overlay: "",
        blend: "multiply",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Light Parchment",
		img: "images/LightParchment.png",
        overlay: "overlays/parchment-paper-light-texture.jpg",
        blend: "hue",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Light Parchment 2",
		img: "images/LightParchment2.png",
        overlay: "overlays/parchment-paper-light-texture.jpg",
        blend: "multiply",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Dark Parchment",
		img: "images/DarkParchment.png",
        overlay: "overlays/black-parchment.jpg",
        blend: "difference",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Outer Space",
		img: "images/OuterSpace.png",
        overlay: "overlays/black-parchment.jpg",
        blend: "lighten",
        hatch: "space1",
        floor: "metal1",
        fullHatch: true,
    },/////
    {
        name: "Cartoon Lava",
		img: "images/CartoonLava.png",
        overlay: "",
        blend: "multiply",
        hatch: "magma1",
        floor: "stone1",
        fullHatch: true,
    },
    {
        name: "Underwater Depths",
		img: "images/UnderwaterDepths.png",
        overlay: "overlays/metal-texture.jpg",
        blend: "darken",
        hatch: "water1",
        floor: "stone1",
        fullHatch: true,
    },
    {
        name: "Beach",
		img: "images/Beach.png",
        overlay: "",
        blend: "multiply",
        hatch: "water1",
        floor: "sand2",
        fullHatch: true,
    },
    {
        name: "Psychedelic",
		img: "images/Psychedelic.png",
        overlay: "overlays/metal-texture.jpg",
        blend: "hue",
        hatch: "water1",
        floor: "",
        fullHatch: true,
    },
    {
        name: "Wood Forest",
		img: "images/WoodForest.png",
        overlay: "",
        blend: "multiply",
        hatch: "hatchingImgGrass",
        floor: "wood1",
        fullHatch: true,
    },
    {
        name: "Blueprint",
		img: "images/Blueprint.png",
        overlay: "overlays/blueprint.png",
        blend: "screen",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "World Map",
		img: "images/worldmap.png",
        overlay: "overlays/parchment-paper-light-texture.jpg",
        blend: "multiply",
        hatch: "w2",
        floor: "d2",
        fullHatch: true,
    },
    {
        name: "Grey Dungeon",
		img: "images/greydungeon.png",
        overlay: "overlays/gray-parchment.jpg",
        blend: "multiply",
        hatch: "hatchingImg",
        floor: "plainWhite",
        fullHatch: true,
    },
    {
        name: "Rock Walls",
		img: "images/rockwalls.png",
        overlay: "",
        blend: "multiply",
        hatch: "r5",
        floor: "plainWhite",
        fullHatch: true,
    },
    {
        name: "Frosty",
		img: "images/frosty.png",
        overlay: "",
        blend: "multiply",
        hatch: "sn1",
        floor: "plainWhite",
        fullHatch: true,
        noGrid: true,
        fillColor: "#d7f6f1"
    },

    {
        name: "Cartoon Taverns",
		img: "images/cartoontaverns.png",
        overlay: "",
        blend: "multiply",
        hatch: "grass3",
        floor: "wood1",
        fullHatch: true,
        noGrid: true,
        softShadowSize: 0,
    },
    
    {
        name: "Parchment Fields",
		img: "images/parchmentfields.png",
        overlay: "overlays/parchment-paper-light-texture.jpg",
        blend: "multiply",
        hatch: "gr2",
        floor: "plainWhite",
        fullHatch: true,
        noGrid: true,
    },
    {
        name: "Rocky Caves",
		img: "images/rockycaves.png",
        overlay: "",
        blend: "multiply",
        hatch: "r2",
        floor: "r2",
        fullHatch: true,
        noGrid: true,
        softShadowSize: 42,
    },
    {
        name: "Stone Castle",
		img: "images/stonecastle.png",
        overlay: "",
        blend: "multiply",
        hatch: "r1",
        floor: "stone1",
        fullHatch: true,
        noGrid: true,
        softShadowSize: 0,
    },
]