var stylePresets = [
    {
        name: "Hand Drawn",
		img: "images/HandDrawn.png",
        overlay: "",
        blend: "multiply",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Light Parchment",
		img: "images/LightParchment.png",
        overlay: "overlays/parchment-paper-light-texture.jpg",
        blend: "hue",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Light Parchment 2",
		img: "images/LightParchment2.png",
        overlay: "overlays/parchment-paper-light-texture.jpg",
        blend: "multiply",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Dark Parchment",
		img: "images/DarkParchment.png",
        overlay: "overlays/black-parchment.jpg",
        blend: "difference",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Outer Space",
		img: "images/OuterSpace.png",
        overlay: "overlays/black-parchment.jpg",
        blend: "lighten",
        hatch: "space1",
        floor: "metal1",
        fullHatch: true,
    },/////
    {
        name: "Cartoon Lava",
		img: "images/CartoonLava.png",
        overlay: "",
        blend: "multiply",
        hatch: "magma1",
        floor: "stone1",
        fullHatch: true,
    },
    {
        name: "Underwater Depths",
		img: "images/UnderwaterDepths.png",
        overlay: "overlays/metal-texture.jpg",
        blend: "darken",
        hatch: "water1",
        floor: "stone1",
        fullHatch: true,
    },
    {
        name: "Beach",
		img: "images/Beach.png",
        overlay: "",
        blend: "multiply",
        hatch: "water1",
        floor: "sand2",
        fullHatch: true,
    },
    {
        name: "Psychedelic",
		img: "images/Psychedelic.png",
        overlay: "overlays/metal-texture.jpg",
        blend: "hue",
        hatch: "water1",
        floor: "",
        fullHatch: true,
    },
    {
        name: "Wood Forest",
		img: "images/WoodForest.png",
        overlay: "",
        blend: "multiply",
        hatch: "hatchingImgGrass",
        floor: "wood1",
        fullHatch: true,
    },
    {
        name: "Blueprint",
		img: "images/Blueprint.png",
        overlay: "overlays/blueprint.png",
        blend: "screen",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "World Map",
		img: "images/worldmap.png",
        overlay: "overlays/parchment-paper-light-texture.jpg",
        blend: "multiply",
        hatch: "w2",
        floor: "d2",
        fullHatch: true,
    },

]