var stylePresets = [
    {
        name: "Hand Drawn",
        overlay: "",
        blend: "multiply",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Light Parchment",
        overlay: "overlays/parchment-paper-light-texture.jpg",
        blend: "hue",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Light Parchment 2",
        overlay: "overlays/parchment-paper-light-texture.jpg",
        blend: "multiply",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Dark Parchment",
        overlay: "overlays/black-parchment.jpg",
        blend: "difference",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },
    {
        name: "Outer Space",
        overlay: "overlays/black-parchment.jpg",
        blend: "lighten",
        hatch: "space1",
        floor: "metal1",
        fullHatch: true,
    },/////
    {
        name: "Cartoon Lava",
        overlay: "",
        blend: "multiply",
        hatch: "magma1",
        floor: "stone1",
        fullHatch: true,
    },
    {
        name: "Underwater Depths",
        overlay: "overlays/metal-texture.jpg",
        blend: "darken",
        hatch: "water1",
        floor: "stone1",
        fullHatch: true,
    },
    {
        name: "Beach",
        overlay: "",
        blend: "multiply",
        hatch: "water1",
        floor: "sand2",
        fullHatch: true,
    },
    {
        name: "Psychedelic",
        overlay: "overlays/metal-texture.jpg",
        blend: "hue",
        hatch: "water1",
        floor: "",
        fullHatch: true,
    },
    {
        name: "Wood Forest",
        overlay: "",
        blend: "multiply",
        hatch: "hatchingImgGrass",
        floor: "wood1",
        fullHatch: true,
    },
    {
        name: "Blueprint",
        overlay: "overlays/blueprint.png",
        blend: "screen",
        hatch: "hatchingImg",
        floor: "",
        fullHatch: false,
    },

]